services:
  - type: web
    name: evan-uv-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /uv/*
        name: Cross-Origin-Resource-Policy
        value: cross-origin
      - path: /epoxy/*
        name: Cross-Origin-Resource-Policy
        value: cross-origin
      - path: /baremux/*
        name: Cross-Origin-Resource-Policy
        value: cross-origin
